# This is a basic workflow to help you get started with Actions

name: mussy-cloud

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
